/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.web;

import org.eclipse.xtext.xbase.web.DefaultXbaseWebModule;

/**
 * Manual modifications go to {@link MyDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyDslWebModule extends DefaultXbaseWebModule {

}
