/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;

/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
	

}
